export const STORE_ADMIN_CREDENTIALS = 'STORE_ADMIN_CREDENTIALS';
export const CLEAR_ADMIN_CREDENTIALS = 'CLEAR_ADMIN_CREDENTIALS';

export const UPDATE_USER = 'UPDATE_USER';
export const CLEAR_USER = 'CLEAR_USER';
