export const STORE_ADMIN_CREDENTIALS = 'STORE_ADMIN_CREDENTIALS';
export const CLEAR_ADMIN_CREDENTIALS = 'CLEAR_ADMIN_CREDENTIALS';

export const UPDATE_USER = 'UPDATE_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const UPDATE_USER_SUBMISSIONS = 'UPDATE_USER_SUBMISSIONS';
export const UPDATE_USER_SUBMISSIONS_ERROR = 'UPDATE_USER_SUBMISSIONS_ERROR';
export const UPDATE_USER_SUBMISSIONS_LOADING = 'UPDATE_USER_SUBMISSIONS_LOADING';
export const UPDATE_DIFFICULTY_FILTERS_AVAILABLE = 'UPDATE_DIFFICULTY_FILTERS_AVAILABLE';
export const UPDATE_DIFFICULTY_FILTERS_SELECTED = 'UPDATE_DIFFICULTY_FILTERS_SELECTED';
export const UPDATE_CATEGORY_FILTERS_AVAILABLE = 'UPDATE_CATEGORY_FILTERS_AVAILABLE';
export const UPDATE_CATEGORY_FILTERS_SELECTED = 'UPDATE_CATEGORY_FILTERS_SELECTED';

export const UPDATE_EVENTS = 'UPDATE_EVENTS';
export const UPDATE_EVENTS_LOADING = 'UPDATE_EVENTS_LOADING';
export const UPDATE_EVENTS_ERROR = 'UPDATE_EVENTS_ERROR';

export const UPDATE_SUBMISSIONS = 'UPDATE_SUBMISSIONS';
export const UPDATE_SUBMISSIONS_LOADING = 'UPDATE_SUBMISSIONS_LOADING';
export const UPDATE_SUBMISSIONS_ERROR = 'UPDATE_SUBMISSIONS_ERROR';
